name: Test Automation Workflow

on:
  push:
    branches: [ main ]
    paths:
      - 'test-automation/**'

jobs:
  test:
    runs-on: ubuntu-24.04  # Especificamos la versión explícitamente
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Actualizado a v4

      - name: Set up Python
        uses: actions/setup-python@v5  # Actualizado a v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html playwright pytest-playwright
          playwright install chromium
          cd test-automation
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run tests
        run: |
          cd test-automation
          pytest tests/test_pickup.py --html=reports/html_reports/report.html --self-contained-html --capture=tee-sys -v

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4  # Actualizado a v4
        with:
          name: test-report
          path: test-automation/reports/html_reports/
          retention-days: 7